;;; private/fsdir/+myproject.el -*- lexical-binding: t; -*-

(fsdir-filelist "myproject")
(fsdir-setq "myproject" "" (concat fsdir-base-dir "sourcecode/myproject/"))
(fsdir-setq "myproject" "art" (concat fsdir-myproject-dir "art/"))
(fsdir-setq "myproject" "codeset" (concat fsdir-myproject-dir "CodeSet/"))
(fsdir-setq "myproject" "docker" (concat fsdir-myproject-dir "docker/"))
(fsdir-setq "myproject" "monorepo" (concat fsdir-myproject-dir "MonoRepo/"))
(fsdir-setq "myproject" "monorepo-clangtest" (concat fsdir-myproject-monorepo-dir "clangtest/"))
(fsdir-setq "myproject" "monorepo-xmake" (concat fsdir-myproject-monorepo-dir "xmake/"))
(fsdir-setq "myproject" "monorepo-cmake" (concat fsdir-myproject-monorepo-dir "cmake/"))
(fsdir-setq "myproject" "monorepo-deno" (concat fsdir-myproject-monorepo-dir "deno/"))
(fsdir-setq "myproject" "monorepo-dotnet" (concat fsdir-myproject-monorepo-dir "dotnet/"))
(fsdir-setq "myproject" "monorepo-emacsmodule" (concat fsdir-myproject-monorepo-dir "emacsmodule/"))
(fsdir-setq "myproject" "monorepo-emake" (concat fsdir-myproject-monorepo-dir "emake/"))
(fsdir-setq "myproject" "monorepo-cargo" (concat fsdir-myproject-monorepo-dir "cargo/"))
(fsdir-setq "myproject" "monorepo-stack" (concat fsdir-myproject-monorepo-dir "stack/"))
(fsdir-setq "myproject" "monorepo-npm" (concat fsdir-myproject-monorepo-dir "npm/"))
(fsdir-setq "myproject" "monorepo-nodejs" (concat fsdir-myproject-monorepo-dir "nodejs/"))
(fsdir-setq "myproject" "monorepo-oclif" (concat fsdir-myproject-monorepo-dir "oclif/"))
(fsdir-setq "myproject" "monorepo-angular" (concat fsdir-myproject-monorepo-dir "angular/"))
(fsdir-setq "myproject" "monorepo-cloudbase" (concat fsdir-myproject-monorepo-dir "cloudbase/"))
(fsdir-setq "myproject" "monorepo-flutter" (concat fsdir-myproject-monorepo-dir "flutter/"))
(fsdir-setq "myproject" "monorepo-golang" (concat fsdir-myproject-monorepo-dir "golang/"))
(fsdir-setq "myproject" "monorepo-lua" (concat fsdir-myproject-monorepo-dir "lua/"))
(fsdir-setq "myproject" "monorepo-elixir" (concat fsdir-myproject-monorepo-dir "elixir/"))
(fsdir-setq "myproject" "monorepo-poetry" (concat fsdir-myproject-monorepo-dir "poetry/"))
(fsdir-setq "myproject" "monorepo-vscode" (concat fsdir-myproject-monorepo-dir "vscode/"))
(fsdir-setq "myproject" "monorepo-sbt" (concat fsdir-myproject-monorepo-dir "sbt/"))
(fsdir-setq "myproject" "monorepo-swift" (concat fsdir-myproject-monorepo-dir "swift/"))
(fsdir-setq "myproject" "monorepo-trpc" (concat fsdir-myproject-monorepo-dir "trpc/"))
(fsdir-setq "myproject" "monorepo-java" (concat fsdir-myproject-monorepo-dir "java/"))
(fsdir-setq "myproject" "monorepo-lein" (concat fsdir-myproject-monorepo-dir "lein/"))
(fsdir-setq "myproject" "monorepo-ruby" (concat fsdir-myproject-monorepo-dir "ruby/"))
(fsdir-setq "myproject" "monorepo-torch" (concat fsdir-myproject-monorepo-dir "torch/"))
(fsdir-setq "myproject" "monorepo-perl" (concat fsdir-myproject-monorepo-dir "perl/"))
(fsdir-setq "myproject" "monorepo-d" (concat fsdir-myproject-monorepo-dir "d/"))
(fsdir-setq "myproject" "monorepo-vue" (concat fsdir-myproject-monorepo-dir "vue/"))
(fsdir-setq "myproject" "monorepo-bun" (concat fsdir-myproject-monorepo-dir "bun/"))

(fsdir-setq "myproject" "rabmono" (concat fsdir-myproject-dir "rabmono/"))
(fsdir-setq "myproject" "rabengine" (concat fsdir-myproject-dir "rabengine/"))

(fsdir-setq "myproject" "unrealproj" (concat fsdir-myproject-dir "UnrealProj/"))
(fsdir-setq "myproject" "unrealproj-python" (concat fsdir-myproject-unrealproj-dir "Content/Python/"))

(fsdir-setq "myproject" "dropbox-mobileorg" (concat "C:/Users/shengfeng/Dropbox/" "mobileorg"))
(fsdir-setq "myproject" "dropbox-Settings" (concat "C:/Users/shengfeng/Dropbox/" "Settings"))

(fsdir-setq "myproject" "unity-hdrp" (concat fsdir-myproject-dir "unity_hdrp/"))
(fsdir-setq "myproject" "unity-std" (concat fsdir-myproject-dir "unity_std/"))
(fsdir-setq "myproject" "unity-urp" (concat fsdir-myproject-dir "unity_urp/"))

(fsdir-setq "myproject" "unity-std-MFShader" (concat fsdir-myproject-unity-std-dir "Assets/Scenes/MFShader/"))
(fsdir-setq "myproject" "unity-std-MFShader-Editor" (concat fsdir-myproject-unity-std-MFShader-dir "Editor/"))
(fsdir-setq "myproject" "unity-std-MFShader-Scripts" (concat fsdir-myproject-unity-std-MFShader-dir "Scripts/"))
(fsdir-setq "myproject" "unity-std-MFShader-Shaders" (concat fsdir-myproject-unity-std-MFShader-dir "Shaders/"))

